---
- hosts: vagrant
  name: Setup Wintermute
  remote_user: ubuntu # or vagrant or whatevs really
  become: yes
  gather_facts: no # Critical for this to work
  vars:
      nginx_ip_address: 192.168.17.10
      git_username: Karim Cheurfi
      git_email: karim.cheurfi@gmail.com
      username: zabana

  pre_tasks:
      - name: "Add man to the sudoers"
        raw: sudo echo "{{username}} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

      - name: "Install Python"
        raw: sudo apt-get install -y python-simplejson

  roles:
      - common
      # - nginx
      # - webdev
