- hosts: wintermute
  name: Setup Wintermute
  remote_user: root # or vagrant or whatevs really
  become: yes
  vars:
      ssh_keys_url: https://github.com/Zabanaa.keys
      git_username: Karim Cheurfi
      git_email: karim.cheurfi@gmail.com
      username: zabana

  roles:
      - common
      - nginx
      - webdev
