---
- hosts: vagrant
  name: Setup Wintermute
  remote_user: ubuntu # or vagrant or whatevs really
  become: yes
  gather_facts: no # Critical for this to work
  vars:
      ssh_keys_url: https://github.com/Zabanaa.keys
      git_username: Karim Cheurfi
      git_email: karim.cheurfi@gmail.com
      username: zabana

  pre_tasks:
      - name: "Add man to the sudoers"
        raw: sudo echo "{{username}} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

      - name: "Install Python"
        raw: sudo apt-get install -y python-simplejson

  roles:
      - common
      - nginx
      - webdev
