---
- name: "Install Necessary Packages"
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - automake
      - pkg-config
      - openssh-server
      - git
      - htop
      - curl
      - wget
      - tree
      - build-dep
      - python3-psycopg2
      - python-psycopg2

- name: "Install Software Dependencies to allow use of add-apt-repository"
  apt: name={{item}} state=present
  with_items:
      - software-properties-common
      - python-software-properties

- name: "Create User {{username}}"
  user:
      name: "{{username}}"
      shell: /bin/bash
      groups: sudo
      append: yes
      system: yes
      home: "/home/{{username}}"
      state: present
  notify: fix home folder permissions

- name: "Add man to the sudoers"
  raw: echo '%sudo	ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

- name: "Copy git config"
  template: src=templates/gitconfig.jinja2 dest=/home/{{username}}/.gitconfig

- name: "Add authorized keys"
  authorized_key:
      user: "{{username}}"
      state: present
      key: "{{ssh_keys_url}}"

- name: "Add fish-shell PPA"
  apt_repository: repo="ppa:fish-shell/release-2" state=present update_cache=yes

- name: "Install fish shell"
  apt: name=fish state=present

- name: "Create fish config directory"
  file: path="/home/{{username}}/.config/fish/functions" state=directory
  notify: fix home folder permissions

- name: "Download Fundle"
  get_url:
      url: https://git.io/fundle-install
      dest: "/home/{{username}}/.config/fish/functions/fundle.fish"

- name: "Download Oh my fish"
  get_url:
      url: http://get.oh-my.fish
      dest: "/home/{{username}}/install"

- name: "Download my fish functions"
  git:
      repo: https://github.com/Zabanaa/plenty-of-fish.git
      dest: "/home/{{username}}/fishfuncs"
      clone: yes
      force: yes

- name: "Install my fish functions"
  shell: cp /home/{{username}}/fishfuncs/*.fish /home/{{username}}/.config/fish/functions

- name: "Change my man's shell to fish"
  command: "/usr/bin/chsh -s /usr/bin/fish {{username}}"

- name: "Download my dotfiles"
  git:
      repo: https://github.com/Zabanaa/dotfiles.git
      dest: "/home/{{username}}/.dotfiles"
      clone: yes
      force: yes

- name: "Install my dotfiles"
  file:
      src: "/home/{{username}}/.dotfiles/{{item.src}}"
      dest: "{{item.dest}}"
      state: link
  with_items:
      - {src: "config.fish", dest: "/home/{{username}}/.config/fish/config.fish"}
      - {src: ".vimrc", dest: "/home/{{username}}/.vimrc"}
      - {src: ".tmux.conf", dest: "/home/{{username}}/.tmux.conf"}

- name: "Create vim colors directory"
  file: path="/home/{{username}}/.vim/colors" state=directory

- name: "Download inkpot colorscheme"
  git:
      repo: https://github.com/ciaranm/inkpot.git
      dest: "/home/{{username}}/inkpot"
      clone: yes
      force: yes

- name: "Install inkpot colour scheme"
  command: "cp /home/{{username}}/inkpot/colors/inkpot.vim /home/{{username}}/.vim/colors/"

- name: "Install Vundle"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{username}}/.vim/bundle/Vundle.vim"
    clone: yes

- name: "Add vim 8 PPA"
  apt_repository:
      repo: 'ppa:jonathonf/vim'

- name: "Install vim 8 (with python3 support)"
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - vim
      - vim-nox

- name: "Install Tmux 2.2+ Dependencies"
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - libevent-dev
      - libncurses-dev
      - build-essential

- name: "Download Tmux"
  git:
      repo: https://github.com/tmux/tmux.git
      dest: /home/{{username}}
      clone: yes
      force: yes

- name: "Compile Tmux"
  shell: autogen.sh
  args:
      chdir: "/home/{{username}}/tmux"

- name: "Install Tmux"
  raw: "cd /home/{{username}}/tmux && ./configure && make"
  notify: move tmux executable to /usr/local/bin
