---
- name: "Install Necessary Packages"
  apt: name={{item}} state=present
  with_items:
      - openssh-server
      - tmux
      - vim
      - htop
      - curl
      - wget
      - tree

- name: "Create User {{username}}"
  user: name={{username}} shell=/bin/bash groups=sudo append=yes state=present
  notify: fix home folder permissions

- name: "Add my man to the sudoers"
  template: src=templates/sudoers.jinja2 dest=/etc/sudoers

- name: "Add fish-shell PPA"
  apt_repository: repo="ppa:fish-shell/release-2" state=present update_cache=yes

- name: "Install fish shell"
  apt: name=fish state=present

- name: "Create fish config directory"
  file: path="/home/{{username}}/.config/fish/functions" state=directory

- name: "Install Fundle"
  get_url:
      url: https://git.io/fundle-install
      dest: "/home/{{username}}/fundle-install"
  notify: install fundle

- name: "Change my man's shell to fish"
  command: "/usr/bin/chsh -s /usr/bin/fish {{username}}"
  become_user: root

- name: "Download Oh my fish"
  get_url:
      url: http://get.oh-my.fish
      dest: "/home/{{username}}/install"
  notify: install omf

- name: "Install Vundle"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{username}}/.vim/bundle/Vundle.vim"
    clone: yes


- name: "download my dotfiles"
  git:
      repo: https://github.com/Zabanaa/dotfiles.git
      dest: "/home/{{username}}/.dotfiles"
      clone: yes

- name: "download and install fish functions"
  git:
      repo: https://github.com/Zabanaa/plenty-of-fish.git
      dest: "/home/{{username}}/fishfuncs"
      clone: yes
  notify: install fish functions

- name: "install dotfiles"
  template: src=templates/install.sh.jinja2 dest="/home/{{username}}/.dotfiles/install.sh"
  notify: install dotfiles
