---
- name: "Install Necessary Packages"
  apt: name={{item}} state=present
  with_items:
      - openssh-server
      - tmux
      - vim
      - htop
      - curl
      - wget
      - tree

- name: "Create User {{username}}"
  user:
      name: "{{username}}"
      shell: /bin/bash
      groups: sudo
      append: yes
      system: yes
      home: "/home/{{username}}"
      state: present
  notify: fix home folder permissions

- name: "Add man to the sudoers"
  raw: echo '%sudo	ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

- name: "Add authorized keys"
  authorized_key:
      user: "{{username}}"
      state: present
      key: "{{ssh_keys_url}}"

- name: "Add fish-shell PPA"
  apt_repository: repo="ppa:fish-shell/release-2" state=present update_cache=yes

- name: "Install fish shell"
  apt: name=fish state=present

- name: "Create fish config directory"
  file: path="/home/{{username}}/.config/fish/functions" state=directory
  notify: fix home folder permissions

- name: "Install git"
  apt: name=git update_cache=yes

- name: "Copy git config"
  template: src=templates/gitconfig.jinja2 dest=/home/{{username}}/.gitconfig

- name: "Download Fundle"
  get_url:
      url: https://git.io/fundle-install
      dest: "/home/{{username}}/.config/fish/functions/fundle.fish"

- name: "Change my man's shell to fish"
  command: "/usr/bin/chsh -s /usr/bin/fish {{username}}"

- name: "Download Oh my fish"
  get_url:
      url: http://get.oh-my.fish
      dest: "/home/{{username}}/install"

- name: "Install Vundle"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{username}}/.vim/bundle/Vundle.vim"
    clone: yes

- name: "Download my fish functions"
  git:
      repo: https://github.com/Zabanaa/plenty-of-fish.git
      dest: "/home/{{username}}/fishfuncs"
      clone: yes
      force: yes

- name: "Install my fish functions"
  shell: cp /home/{{username}}/fishfuncs/*.fish /home/{{username}}/.config/fish/functions

- name: "download my dotfiles"
  git:
      repo: https://github.com/Zabanaa/dotfiles.git
      dest: "/home/{{username}}/.dotfiles"
      clone: yes
      force: yes

- name: "Create install script for my dotfiles"
  template: src=templates/install.sh.jinja2 dest="/home/{{username}}/.dotfiles/install.sh"

- name: "Download seattle colorscheme"
  git:
      repo: https://github.com/mbbill/vim-seattle.git
      dest: "/home/{{username}}/seattle"
      clone: yes
      force: yes

- name: "Create vim colors directory"
  file: path="/home/{{username}}/.vim/colors" state=directory

- name: "Install seattle colour scheme"
  command: "cp /home/{{username}}/seattle/colors/seattle.vim /home/{{username}}/.vim/colors/"

- name: "Install my dotfiles"
  file:
      src: "/home/{{username}}/.dotfiles/{{item.src}}"
      dest: "{{item.dest}}"
      state: link
  with_items:
      - {src: "config.fish", dest: "/home/{{username}}/.config/fish/config.fish"}
      - {src: ".vimrc", dest: "/home/{{username}}/.vimrc"}
      - {src: ".tmux.conf", dest: "/home/{{username}}/.tmux.conf"}

# - stat: path="/home/{{username}}/.local/share/omf"
#   register: omf

# - shell: fish install
#   args:
#       chdir: /home/zabana
#   when: omf.stat.isdir is not defined
#   become: yes
#   become_user: zabana
#   register: omgomf

# - debug: var=omgomf
