---
- name: "Update Apt"
  raw: sudo apt-get update

- name: "Install Necessary Packages"
  apt: name={{item}} state=present
  with_items:
      - openssh-server
      - tmux
      - vim
      - htop
      - curl
      - wget
      - tree

- name: "Create User Zabana"
  user: name=zabana shell=/bin/bash groups=sudo append=yes state=present

- name: "Add my man to the sudoers"
  template: src=templates/sudoers.jinja2 dest=/etc/sudoers

- name: "Add fish-shell PPA"
  apt_repository: repo="ppa:fish-shell/release-2" state=present update_cache=yes

- name: "Install fish shell"
  apt: name=fish state=present

- name: "Download oh-my-fish"
  git:
      repo: https://github.com/oh-my-fish/oh-my-fish
      dest: /home/ubuntu/oh-my-fish
      clone: yes

- name: "Create fish config directory"
  file: path=/home/ubuntu/.config/fish/functions state=directory

- name: "Change my man's shell to fish"
  command: /usr/bin/chsh -s /usr/bin/fish zabana

- name: "Download Oh my fish"
  git: repo=https://github.com/oh-my-fish/oh-my-fish dest=/home/ubuntu/oh-my-fish clone=yes

- name: "Install Vundle"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/ubuntu/.vim/bundle/Vundle.vim
    clone: yes

- name: "Copy my vimrc"
  copy: src=~/.dotfiles/.vimrc dest=~/.vimrc

- name: "Copy my tmux conf"
  copy: src=~/.tmux.conf dest=~/.tmux.conf

- name: "Copy my fish shell conf"
  copy: src=~/.dotfiles/config.fish dest=/home/ubuntu/.config/fish/config.fish

- name: "Copy my fish functions"
  copy: src={{item}} dest=/home/ubuntu/.config/fish/functions
  with_fileglob:
      - ~/.config/fish/functions/*.fish
